# Generated by Django 4.0.5 on 2022-06-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instasocial', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
